# Generated by Django 6.0.6 on 2026-06-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='book',
            name='full_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/full/'),
        ),
        migrations.AddField(
            model_name='book',
            name='sample_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/samples/'),
        ),
    ]
