# Generated by Django 6.0.6 on 2026-06-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_book_cover_image_alter_book_full_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
